services:
  postgres:
    image: 'postgres:16-bullseye'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo
    volumes:
      - postgres-data:/var/lib/postgres/data

volumes:
  postgres-data:
